services:
  - type: web
    name: spotify-playlist-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn spotify_api.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: spotify-db
          property: connectionString
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false

databases:
  - name: spotify-db
    databaseName: spotify
    user: spotify
